[gcp_service_account]
type = "service_account"
project_id = "sapient-tractor-459508-i8"
private_key_id = "d8e2291b5f70d5fd35c4ae3ff368a68f52c98a86"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCX9HXJGTszTwr
RBsUtIcAEXfR3Wwudq80c4Ix/86of/CSeX9BT2EckS7ybjEsYUbU/NxsPTEc2Mdn
ilN/0MsZO79J2jYcwVOPzwmzI/2400ZPRyP+eRq/uyMwjSqvZhLIWxhUL5d6vU59
VqBZgDDY4WDpZjAF+cT869IuqgKHEmdCko3AHFC/gXFD2IUJT0CEQPsNemaPGYwe
pukQj2kL8VI2b11e6WUW62D3AFUSndD8kqay+sfmWBA2n0M3HvBtL2XrNR2CY5Bs
W0z5ycIzhiBz5FygKlFhZeLqvVqi3etc9CtumG3foFNp5MprrhJvm+ucXpIspbO9
8S4djd5RAgMBAAECggEABDab6T3ChLHyMvHkyfvomgmTslRKMW7X+QGwxpd7I4K0
DhWQh5oXF2c72eKl/qAUYmHuZgsLH7GNqPxO0QxCl5QIknfZ1aFVlJFyIWFcJGYY
AquFGtGfN2nw2lWR1LMYU+8XLB2X+zLtTgds4TCUXnvylzyXn+ZV7P5joPVSEE49
8j/LekmxlVIeKk0RaO5Qxn/oHAlYn5QPoutSkY4rx8SQT8PPXXOn3VAOtb4yJE0/
uzv0NiBu1YqWVcxaGYzXHzm9FErqzz6VWL4+XriQ1VgRdPngseBnCChi4Bisng69
wZ23OUEcHZF7YbsQXyNcM8m3gmyw52pzkh35yzlq3QKBgQDjIXd+KWJa9+FOFDeI
z7Q5jFRhFikLoPBpsH6dDG1KwNMyqwvOY9wm5zJXYYK02o0WdZZZM44QWtb8S1yO
lKqWlh5RqJTFtsz3b3uxNES/ykySxYPlYALbJzn2v+cukiy0TC7unlBkOdhGOo7C
3sURHmJChmNblskmuOju12JqKwKBgQDbFIB+Znj3Ex0KWa7OF7RPFX/KqvkB9VqL
UEAtJqKwRVx1xIc3PtdgZSZYlgMklJWka0plRTXVWwZqh0RPTfwkDg318a27WQPN
w+TsE9k1rYEhg4kkuYXn8bCMPz609ixmrvpa4JV+1tV3wZUnst+uZWMEpA4lzpko
CcNjftMHcwKBgQCeZ/nZoG07OoQFG2572Tg9ppQ2vejUdmMVowU67K7QotjpDogG
YnjpHPdsH9Kz5XTexBWekqky2Nf1T2329tJegcYVd3iCx/H9Y+Alf2mvRRzQhDZv
4906EQqI/9/xB/trp3JX80voCru+hxqH6CwSu1kWQnnLJ8eUXQP/h3HYzwKBgH48
Ywnye/NKdSpYoOwqJoCHT9p1CASD3wd1V3Vs1MOjQ/KsKom/0RS/VAgpcGgsocla
9URDTBDDYYASr17O/eG8o3i7KLNSSGnRXeBWU4uljUnFZEngCPOshWFatARL8Su9
2Y5x6FJs8hYOWqbEYDU6QIMVEP3h/MhgT9DN7EVXAoGBANI8YRSG7Tq6sfiyepgx
1vpkckmxiWr8ABB3ytGE0BILOcr37RvO+RSfAKBuyXNdtj+TFa3C+GI1R5ETY6OM
XaSteeE5W8X03xVymPZE96rMygdmZgFX7n1RjQT/CTdPqchaO/4fQGnARfdJXdUD
prKNGIyOJ/Ik32ss065fTntb
-----END PRIVATE KEY-----"""
client_email = "streamlit-writer@sapient-tractor-459508-i8.iam.gserviceaccount.com"
client_id = "110640399152746027485"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-writer%40sapient-tractor-459508-i8.iam.gserviceaccount.com"
